language: cpp
sudo: required
compiler:
  - gcc

before_install:
  - sudo apt-get install libeigen3-dev
  - git clone https://github.com/google/googletest.git
  - mkdir -p googletest/build && cd googletest/build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - sudo cmake --build . --parallel 4 --target install

install:
  - mkdir build && cd build
  - cmake -D BUILD_EXAMPLE=ON -D BUILD_TESTS=ON .. 
  - cmake --build . --parallel 4

script:
  - ctest . --output-on-failure

branches:
  only:
    - master
    - dev

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
